name: "External device client"
description: "This is the addon installed on the extern device"
version: "1.0.0"
slug: "external_client"
init: false
arch:
  - aarch64
  - amd64
startup: services
ports:
  50051/tcp: 50051
#websocket_url: "ws://0.0.0.0:3000"
device_id: "abcde"
hassio_api: true
host_dbus: true
host_network: true
# Hvis ingress er nødvendigt