name: "External gRPC addon"
description: "addon hosting the gRPC on the external device"
version: "1.0.0"
slug: "grpc-external"
init: false
arch:
  - aarch64
  - amd64
startup: services
ports:
  8080/tcp: 8080
  3030/tcp: 3030
  5000/tcp: 5000
  50051/tcp: 50051
  1935/tcp: 1935
  8554/tcp: 8554
  1234/tcp: 1234
  9000/tcp: 9000
hassio_api: true
host_dbus: true
host_network: true
ingress: true
ingress_port: 3030
ingress_entry: "/app"
ingress_stream: true
map:
  - media:rw
  - share:rw
apparmor: false
uart: true