name: "Distribute Test"
description: "GStreamer test server for video distribution"
version: "1.0.2"
slug: "distribute-test"
init: false
arch:
  - aarch64
  - amd64
startup: services
#image: local/{aarch64}-distribute-video:latest
ports:
  8080/tcp: 8080
  9123/tcp: 9123
  3030/tcp: 3030
#websocket_url: "ws://0.0.0.0:3000"
hassio_api: true
host_dbus: true
host_network: true
# Hvis ingress er nødvendigt
ingress: true
ingress_port: 3030
ingress_entry: "/app"
ingress_stream: true
video: true
usb: true
privileged:
  - DAC_READ_SEARCH
  - SYS_ADMIN
map:
  - media:rw
  - share:rw
# device_id: "abcde"
devices: 
 - /dev/video0:/dev/video0
 - /dev/video1:/dev/video1
apparmor: false
uart: true